//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisakiEQ.Struct.jma.Area.@static {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisakiEQ.Struct.jma.Area.static.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   100,石狩地方北部,いしかりちほうほくぶ
        ///101,石狩地方中部,いしかりちほうちゅうぶ
        ///102,石狩地方南部,いしかりちほうなんぶ
        ///105,渡島地方北部,おしまちほうほくぶ
        ///106,渡島地方東部,おしまちほうとうぶ
        ///107,渡島地方西部,おしまちほうせいぶ
        ///110,檜山地方,ひやまちほう
        ///115,後志地方北部,しりべしちほうほくぶ
        ///116,後志地方東部,しりべしちほうとうぶ
        ///117,後志地方西部,しりべしちほうせいぶ
        ///119,北海道奥尻島,ほっかいどうおくしりとう
        ///120,空知地方北部,そらちちほうほくぶ
        ///121,空知地方中部,そらちちほうちゅうぶ
        ///122,空知地方南部,そらちちほうなんぶ
        ///125,上川地方北部,かみかわちほうほくぶ
        ///126,上川地方中部,かみかわちほうちゅうぶ
        ///127,上川地方南部,かみかわちほうなんぶ
        ///130,留萌地方中北部,るもいちほうちゅうほくぶ
        ///131,留萌地方南部,るもいちほうなんぶ
        ///135,宗谷地方北部,そうやちほうほくぶ
        ///136,宗谷地方南部,そうやちほうなんぶ
        ///139,北海道利尻礼文,ほっかいどうりしりれぶん
        ///140,網走地方,あ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaForecastLocalE {
            get {
                return ResourceManager.GetString("AreaForecastLocalE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   110100,札幌中央区,さっぽろちゅうおうく
        ///110200,札幌北区,さっぽろきたく
        ///110300,札幌東区,さっぽろひがしく
        ///110400,札幌白石区,さっぽろしろいしく
        ///110500,札幌豊平区,さっぽろとよひらく
        ///110600,札幌南区,さっぽろみなみく
        ///110700,札幌西区,さっぽろにしく
        ///110800,札幌厚別区,さっぽろあつべつく
        ///110900,札幌手稲区,さっぽろていねく
        ///111000,札幌清田区,さっぽろきよたく
        ///120200,函館市,はこだてし
        ///120300,小樽市,おたるし
        ///120400,旭川市,あさひかわし
        ///120500,室蘭市,むろらんし
        ///120600,釧路市,くしろし
        ///120700,帯広市,おびひろし
        ///120800,北見市,きたみし
        ///120900,夕張市,ゆうばりし
        ///121000,岩見沢市,いわみざわし
        ///121100,網走市,あばしりし
        ///121200,留萌市,るもいし
        ///121300,苫小牧市,とまこまいし
        ///121400,稚内市,わっかないし
        ///121500,美唄市,びばいし
        ///121600,芦別市,あしべつし
        ///121700,江別市,え [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaInformationCity {
            get {
                return ResourceManager.GetString("AreaInformationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100,123500,123500,石狩市花川,いしかりしはなかわ
        ///100,123500,123501,石狩市聚富,いしかりししっぷ
        ///100,123500,123520,石狩市厚田,いしかりしあつた
        ///100,123500,123521,石狩市浜益,いしかりしはまます
        ///100,123500,123522,石狩市花畔,いしかりしばんなぐろ
        ///100,130300,130320,当別町白樺,とうべつちょうしらかば
        ///100,130400,130431,新篠津村第４７線,しんしのつむらだいよんじゅうななせん
        ///101,110100,110100,札幌中央区北２条,さっぽろちゅうおうくきたにじょう
        ///101,110100,110140,札幌中央区南４条,さっぽろちゅうおうくみなみよじょう
        ///101,110200,110220,札幌北区太平,さっぽろきたくたいへい
        ///101,110200,110240,札幌北区篠路,さっぽろきたくしのろ
        ///101,110200,110241,札幌北区新琴似,さっぽろきたくしんことに
        ///101,110300,110341,札幌東区元町,さっぽろひがしくもとまち
        ///101,11040 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObservationPoint {
            get {
                return ResourceManager.GetString("ObservationPoint", resourceCulture);
            }
        }
    }
}
